services:
  mongodb:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  signalgenerator:
    build: ./signalgenerator
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb

  featureextractor:
    build: ./featureextractor
    ports:
      - "8100:8100"
    env_file:
      - .env
    depends_on:
      - mongodb

  faultclassifier:
    build: ./faultclassifier
    ports:
      - "8001:8001"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - signalgenerator
      - featureextractor
      - faultclassifier

volumes:
  mongodb_data:
